In [ ]:
#%debug
%load_ext autoreload
%autoreload 2

import os
from os.path import join as pjoin
if 'DATA_TMP_MEMORY_ERRORS_STAB_AND_STOCH' not in os.environ:
    os.environ['DATA_TMP_MEMORY_ERRORS_STAB_AND_STOCH'] = os.path.expandvars('$HOME') + '/ju_lyon/memerr/data2'


import os,sys; sys.path.append(os.path.expandvars('$CODE_MEMORY_ERRORS'))
#%run -i ../exec_HPC.py 0
from config2 import path_code
from IPython import get_ipython; ipython = get_ipython()

locs = {}

from config2 import subjects

import numpy as np
from os.path import join as pjoin
dir_rr = '/home/demitau/ownCloud/Current/merr_data/Romain_calc_res/'
#an = 'prevfeedback_preverrors_errors_prevbelief'
#random = pjoin(dir_rr, f'sub01_WGPOZPEE_randompartial_scores_{an}_broad.npy')
#stable = pjoin(dir_rr, f'sub01_WGPOZPEE_stablepartial_scores_{an}_broad.npy')
#scores_romain_b2b = {}
#scores_romain_b2b['stable'] = np.load(stable)# 5 splits each
#scores_romain_b2b['random'] = np.load(random)
#display(scores_romain_b2b)
#print(an.split('_'))
# time_lock = target,  control = feedback    ( I had control = movement)


rcrd = '/home/demitau/current/merr_data/Romain_calc_res/'
fnfs = [ rcrd + 'sub01_X_random.npy',
rcrd + 'sub01_X_stable.npy',
rcrd + 'sub01_Y_random.npy',
rcrd + 'sub01_Y_stable.npy',
rcrd + 'sub01_partialscores_random.npy',
rcrd + 'sub01_partialscores_stable.npy']      
fs = [ np.load(fnf) for fnf in fnfs ]

an = 'prevmovement_preverrors_errors_prevbelief_broad'
print(an)
(X_random_romain, X_stable_romain, Y_random_romain, 
 Y_stable_romain, sc_b2b_random, sc_b2b_stable) = fs

scores_romain_b2b = dict(list(zip(['scores_b2b_random', 'scores_b2b_stable'] , [sc_b2b_random, sc_b2b_stable])))
display(scores_romain_b2b)

In [ ]:
# Romain wants:
# prevmovement_preverrors_errors_prevbelief_broad 
# prevfeedback_preverrors_errors_prevbelief_broad
# i.e.
#getAnalysisVarnames('target','feedback')
#getAnalysisVarnames('target','movement')

In [ ]:
for f in fs:
    print(f.shape)

# Sim

In [ ]:
behav_df_full.columns

In [ ]:
es_fnf = '/home/demitau/ju_lyon/memerr/data2/sub99/df.pkl.zip'
fif_fnf = '/home/demitau/ju_lyon/memerr/data2/sub99/raw_VisuoMotor_no_filter_with_ICA_broad.fif'

In [ ]:
scr = pjoin('dec_err_sens_sliding2.py' )
#'--slide_window_dur 0.464 --slide_window_shift 0.232'
envstr = 'stable'
s = (
  '--param_file dec_err_sens_sliding.ini --random_seed 0' 
  ' --output_folder corr_spoc_es_sliding2_no_filter --hpass no_filter' 
  ' --slide_windows_type explicit --use_preloaded_flt_raw 0' 
  ' --tmin -0.5 --tmax 0 --control_type movement'
  ' --trial_group_col_calc trials --trim_outliers 0' 
  ' --dists_rad_from_prevtgt all --dists_trial_from_prevtgt all'
  ' --subject sub99 --time_locked target' 
  ' --regression_type Ridge --freq_name broad' 
 f' --freq_limits 4,60 --env_to_run {envstr}' 
  ' --custom_suffix trim0_we_drall_dtall'
  f' --behav_file {es_fnf}'
  f' --fif_file {fif_fnf}'
)

#%debug
for subject in ['sub99']:
#for subject in subjects[1:]:
    print('   ', subject)
    n_jobs = 10
    hpass = 'no_filter'
    regression_type = 'Ridge'
    ipython.run_line_magic('run',
        f' -i {path_code}/{scr} ' + s)

In [ ]:
subdf[['prev_movement', 'prev_error', 'error', 'prev_belief']]

In [ ]:
behav_df_cur[['prev_movement', 'prev_error', 'error', 'prev_belief']]

In [ ]:
#behav_df_full

In [ ]:
fn_flt_raw_full

In [ ]:
load_flt_raw and os.path.exists(fn_flt_raw_full) 

In [ ]:
 os.path.exists(fn_events_full) and \
    (not (use_preloaded_flt_raw and preloaded_flt_raw_is_present) )

In [ ]:
load_flt_raw

In [ ]:
fn_events_full

# New

In [ ]:
#control = movement
#broad
#no_filter
#with_ICA
#sub1
#an = prevmovement_preverrors_errors_prevbelief_broad

# he invalidates first trial of each block

In [ ]:
nskip_trial

In [ ]:
#es_fnf = '/home/demitau/ownCloud/Current/merr_data/df_all_multi_tsz_NIH.pkl.zip'
es_fnf = '/home/demitau/data_Quentin/full_experiments/data2/df_all_multi_tsz.pkl.zip'

fif_fnf = '/home/demitau/ownCloud/Current/merr_data/raw_VisuoMotor_no_filter_with_ICA.fif'

In [ ]:
scr = pjoin('dec_err_sens_sliding2.py' )
#'--slide_window_dur 0.464 --slide_window_shift 0.232'
#envstr = 'stable'

#discard_hit_twice = 1
discard_hit_twice = 0
scores_list = []
for envstr in ['stable']: #, 'random']:
    s = (
      '--param_file dec_err_sens_sliding.ini --random_seed 1' 
      ' --output_folder corr_spoc_es_sliding2_no_filter --hpass no_filter' 
      ' --slide_windows_type explicit --use_preloaded_flt_raw 1' 
      ' --tmin -0.5 --tmax 0 '
      ' --safety_time_bound 0.05'
      ' --control_type feedback --time_locked target '
      ' --trial_group_col_calc trialwe --trim_outliers 0' 
      ' --dists_rad_from_prevtgt all --dists_trial_from_prevtgt all'      
      ' --subject sub01_WGPOZPEE ' 
     f' --each_SPoC_fit_is_parallel 1 '
     f' --scale_X_robust 1 --scale_Y_robust 1  '
     f' --discard_hit_twice {discard_hit_twice} '
      ' --n_jobs 12 '
      ' --regression_type Ridge --freq_name broad' 
     f' --freq_limits 4,60 --env_to_run {envstr}' 
      ' --custom_suffix trim0_drall_dtall'
     f' --behav_file {es_fnf}'
     f' --fif_file {fif_fnf}'
    )

    #%debug
    for subject in subjects[:1]:
    #for subject in subjects[1:]:
        print('   ', subject)
        n_jobs = 10
        hpass = 'no_filter'
        regression_type = 'Ridge'
        ipython.run_line_magic('run',
            f' -i {path_code}/{scr} ' + s)
        
    scores = svd['decoding_per_var_b2b']\
        ['prev_movement,prev_error,error,prev_belief']['scores']
    scores_list += [scores]
    print( envstr, scores )

In [ ]:
scores_fb = svd['decoding_per_var_b2b']['prev_feedback,prev_error,error,prev_belief']['scores']
print(scores_fb)

In [ ]:
each_SPoC_fit_is_parallel

In [ ]:
#        discard_hit_twice = 1   
# each_SPoC_fit_is_parallel 1,  seed 1
#  scores_list =
# [array([0.00035778, 0.02235245, 0.04191405, 0.05811763]),
#  array([ 0.00422811,  0.02095435, -0.00199676, -0.01069064])]

# each_SPoC_fit_is_parallel 0 or 1 gives same numbers


#seed 0 stable [0.00189148 0.02553717 0.05343451 0.05780295]

#     discard_hit_twice = 0
# seed 1 stable [-0.00838634  0.01870682  0.04528066  0.06920459]

#robust scale X and Y
#discard_hit_twice = 0
#each_SPoC_fit_is_parallel 1
#seed 1 [ 0.24063552 -0.00430724  0.04308413  0.02089529]

#robust scale X and Y
#discard_hit_twice = 0
#each_SPoC_fit_is_parallel 1
#control feedback 
#array([0.12825361, 0.00162739, 0.04308413, 0.03051465])

# we
# [0.12825361 0.00162739 0.04308413 0.03051465]

In [ ]:
scores_list

In [ ]:
SPoC_n_components

In [ ]:
n_splits_B2B

In [ ]:
display(scores_romain_b2b)

In [ ]:
addvars

In [ ]:
addvar_dict

In [ ]:
target_coords

In [ ]:
delay_trig_photodi, use_non_hit

In [ ]:
behav_df_cur['environment']

In [ ]:
#behav_df_full['feedback']

In [ ]:
len(behav_df_cur['non_hit_not_adj']), behav_df_cur['non_hit_not_adj'].sum()

In [ ]:
behav_df_cur['feedbackX']

In [ ]:
from base2 import point_in_circle, radius_target, radius_cursor
targets_stable = behav_df_cur['target_inds'].values
feedbackX_stable, feedbackY_stable = behav_df_cur[['feedbackX','feedbackY']].values.T

non_hit_stable = point_in_circle(targets_stable, target_coords,
                                 feedbackX_stable, feedbackY_stable,
                                 radius_target + radius_cursor)
non_hit_stable = np.array(non_hit_stable)
non_hit = non_hit_stable.copy()
non_hit = ~(~non_hit | ~np.insert(non_hit, 0, 1)[:-1])
non_hit[[0, 192]] = False  # Removing first trial of each block



In [ ]:
non_hit.sum(), non_hit_stable.sum()

In [ ]:
behav_df_cur

In [ ]:
non_hit.sum()

In [ ]:
len(behav_df_cur)

In [ ]:
behav_df_cur['non_hit_not_adj'].sum(), behav_df_cur['non_hit_shifted'].sum()

In [ ]:
safety_time_bound

In [ ]:
tmin_cur, tmax_cur

In [ ]:
#['prev_movement', 'prev_error', 'error', 'prev_belief']
from datetime import datetime
for env in ['stable']: #, 'random']:
    Y = []
    Xs = []
    #for varn in vars_to_decode_b2b_tmp:
    fnf = pjoin(results_folder, f'Xy_b2b_{env}.npz')
    s = str( datetime.fromtimestamp(os.stat(fnf).st_mtime ) )
    print(s)
    r = np.load( fnf )
    X=r['X']
    y = r['y'].T
    Y += [y]
    Xs += [X]
    print(X.shape, y.shape, r['varnames'])

    Y = np.vstack(Y).T
        
    print( Y.shape, X.shape )
    
    if env == 'stable':
        X_stable = X
        Y_stable = Y        
    if env == 'random':
        X_random = X
        Y_random = Y
        
print('dif stable =', np.abs( Y_stable - Y_stable_romain ).max() )
print('dif random =', np.abs( Y_random - Y_random_romain ).max() )

In [ ]:
#['prev_movement', 'prev_error', 'error', 'prev_belief']
from datetime import datetime
for env in ['stable', 'random']:
    Y = []
    Xs = []
    for varn in vars_to_decode_b2b_tmp:
        fnf = pjoin(results_folder, f'Xy_classical_{env}_{varn}.npz')
        s = str( datetime.fromtimestamp(os.stat(fnf).st_mtime ) )
        print(s)
        r = np.load( fnf )
        X=r['X']
        y = r['y']
        Y += [y]
        Xs += [X]
        print(varn, X.shape, y.shape, r['varname'])

    Y = np.vstack(Y).T
        
    print( Y.shape, X.shape )
    
    if env == 'stable':
        X_stable = X
        Y_stable = Y        
    if env == 'random':
        X_random = X
        Y_random = Y
        
print('dif stable =', np.abs( Y_stable - Y_stable_romain ).max() )
print('dif random =', np.abs( Y_random - Y_random_romain ).max() )

In [ ]:
behav_df_cur

In [ ]:
192*2

In [ ]:
behav_df_cur.query('trials in [192,383]')[['trials','non_hit_not_adj'] ]

In [ ]:
non_hit[[0,192]]

In [ ]:
Y_random_romain[190:195,:1]

In [ ]:
Y[190:195,:1]

In [ ]:
for vi in range(1,len(Xs)):
    dif = np.abs( Xs[0] - Xs[vi] ).max()
    
    dif2 = np.abs( Xs[0] - X_stable_romain ).max()
    print(vi,dif, dif2)

In [ ]:
mismatch = Xs[0] - X_stable_romain
print(mismatch.std() / X_stable_romain.std())

In [ ]:
np.abs( mismatch / Xs[0] ).std()

In [ ]:
np.abs( mismatch / X_stable_romain ).std()

In [ ]:
np.abs( mismatch / X_stable_romain ).std()

In [ ]:
fif_fnf

In [ ]:
import scipy
np.median( np.abs( Xs[0] - X_stable_romain ) )

In [ ]:
np.median(np.abs( Xs[0]) ), np.median(np.abs( X_stable_romain) )

In [ ]:
import matplotlib.pyplot as plt
import matplotlib as mpl

In [ ]:
import matplotlib.pyplot as plt
nts = np.arange(136,195)
chi = 4
#ts = slice(None,1000,20)
ts = slice(None,1)
c = 1e15
pairs = [(X_stable,X_stable_romain)] #, (X_random,X_random_romain)]
for X1,X2 in pairs:
    vs = X1[nts,chi,ts] *c
    vs_romain = X2[nts,chi,ts] * c
    display( vs )
    display( vs_romain )

    #plt.plot(vs.T, ls='-', c='blue')
    #plt.plot(vs_romain.T, ls='--', c='orange')

    plt.figure()
    plt.plot(nts, vs, ls='-', c='blue')
    plt.plot(nts, vs_romain, ls='--', c='orange')


In [ ]:
sl = np.arange(120,150)
list( zip(sl,Y_random[sl,0]- Y_random_romain [sl,0],  Y_random[sl,0], Y_random_romain [sl,0] )) 

In [ ]:
vs.shape

In [ ]:
import numpy as np
eps = np.finfo(float).eps
print(eps)

In [ ]:
X_stable_romain.std()

In [ ]:
import gc; gc.collect()

In [ ]:
print('dif stable =', np.abs( Y - Y_stable_romain ).max() )

In [ ]:
i = 5
for vi in range(4):
    print( Y[:i,vi] )
    print( Y_stable_romain[:i,vi] )

In [ ]:
Y_random_romain.shape

In [ ]:
Y_stable_romain.shape

In [ ]:
an.split('_')[:-1]

In [ ]:
Y_stable_romain.shape
#X_random_romain, X_stable_romain, Y_random_romain, Y_stable_romain

In [ ]:
vars_to_decode_classic

In [ ]:
control_type

In [ ]:
vars_to_decode_b2b_tmp

In [ ]:
fn_events_full

In [ ]:
fn_flt_raw_full

In [ ]:
fif_fnf

In [ ]:
vars_to_decode_b2b

In [ ]:
os.path.split( fname_full )[0]

In [ ]:
par['recalc_err_sens']

In [ ]:
vndef2vn

In [ ]:
behav_df_cur['environment'].unique()

In [ ]:
computeErrSensVersions

In [ ]:
len(behav_df_full), len(behav_df_cur)

In [ ]:
(behav_df_full['trials'].diff().iloc[1:] > 0).all()

In [ ]:
stage2evn2event_ids['target']

In [ ]:
env2envcode

In [ ]:
meg_targets_ev = epochs_for_EC.events[:,2].copy()
for env,envcode in env2envcode.items():
   #trial_inds = np.where(environment == envcode)[0]
   trial_inds = np.where( np.isin(meg_targets_ev,
       stage2evn2event_ids['target'][env] ) )[0] 
   print(env,len(trial_inds), trial_inds[0], trial_inds[-1] )
   # it uses that  target codes are conequitive integers
   meg_targets_ev[trial_inds] = meg_targets_ev[trial_inds] - env2subtr[env]


In [ ]:
behav_df_cur2 = enforceTargetTriggerConsistency(behav_df_full.copy(),
                               epochs_for_EC,
                               behav_df_full['environment'], save_fname = None)


In [ ]:
B = np.array( [meg_targets_ev, behav_df_full['target_inds']] ).T
B[:,0] - B[:,1]

In [ ]:
behav_df_full.sort_values('trials')

In [ ]:
behav_df_full[['trials','target_inds']].iloc[192:199]

In [ ]:
A = np.array( [epochs_for_EC.events[:,2], behav_df_full['target_codes']] ).T
A[:,0] - A[:,1]

Ac = A + np.array([0,5])[None,:]

display( Ac[192: 199] )

A[192: 199] #- np.array([0,-5])[None,:]
#
#B[190:220]

In [ ]:
len(epochs_for_EC), len(behav_df_full)

In [ ]:
set(behav_df_full['target_codes'].unique())

In [ ]:
behav_df_cur['target_inds']

In [ ]:
behav_df_cur['target_codes']

In [ ]:
set( epochs_for_EC.events[:,2] )

In [ ]:
len(behav_df_full)

In [ ]:
behav_df_full['trigger_present'].sum() / len( behav_df_full['trigger_present'])

In [ ]:
#behav_df_full['err_sens']

In [ ]:
behav_df_full.columns

In [ ]:
behav_df_full.query('trial_shift_size == 1 and trial_group_calc == "trials"').duplicated(['subject','trials'] ).sum()

In [ ]:
behav_df_cur[['RT','movement_duration']]

In [ ]:
vars_to_decode_b2b_tmp

In [ ]:
behav_df_cur.belief

In [ ]:
behav_df_cur.columns

In [ ]:
behav_df_cur['non_hit_not_adj']

In [ ]:
epochs_for_EC.events

# Read XY

In [ ]:
import numpy as np
fnf = '/home/demitau/data_Quentin/full_experiments/data2/sub01_WGPOZPEE/results/spoc_home2_no_filter_orig/with_ICA;no_filter;broad;movement;target;stable_XY.npz'
f = np.load(fnf)
# tmax_safe was = +0.05 in this data

import numpy as np
from sklearn.model_selection import ShuffleSplit

X_desired = f['X'] # trial x sensors x time
Y_desired = f['Y']
print( X_desired.shape)  # trial x sensors x time 
print( Y_desired.shape)  # trial x  dim

In [ ]:
fnf  = '/home/demitau/ownCloud/Current/NeuroSci/Romain/code_memory_errors/exper_protocol/tis.npz'
f = np.load(fnf, allow_pickle = 1)